// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEp8s4C6dz7j6u-mGC_Btulx3Fi6ZBwVs',
    appId: '1:981188695775:web:49f8f14c4011a1b258fb6a',
    messagingSenderId: '981188695775',
    projectId: 'smart-feeding-app',
    authDomain: 'smart-feeding-app.firebaseapp.com',
    storageBucket: 'smart-feeding-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAheIkFvAIuXzDc-cOUEcId_Q9mBC_6UbY',
    appId: '1:981188695775:android:8248d7159c72d12858fb6a',
    messagingSenderId: '981188695775',
    projectId: 'smart-feeding-app',
    storageBucket: 'smart-feeding-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4TZZDqrjkIoGxDT_6dazrqAqDR83Qvw',
    appId: '1:981188695775:ios:5a9bc36c383712c058fb6a',
    messagingSenderId: '981188695775',
    projectId: 'smart-feeding-app',
    storageBucket: 'smart-feeding-app.firebasestorage.app',
    iosBundleId: 'com.example.smartFeedingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4TZZDqrjkIoGxDT_6dazrqAqDR83Qvw',
    appId: '1:981188695775:ios:5a9bc36c383712c058fb6a',
    messagingSenderId: '981188695775',
    projectId: 'smart-feeding-app',
    storageBucket: 'smart-feeding-app.firebasestorage.app',
    iosBundleId: 'com.example.smartFeedingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEp8s4C6dz7j6u-mGC_Btulx3Fi6ZBwVs',
    appId: '1:981188695775:web:d5497ad878174b2658fb6a',
    messagingSenderId: '981188695775',
    projectId: 'smart-feeding-app',
    authDomain: 'smart-feeding-app.firebaseapp.com',
    storageBucket: 'smart-feeding-app.firebasestorage.app',
  );
}
